server:
  port: 8008

mybatis:
  mapper-locations: 'classpath:mapper/*.xml'
  type-handlers-package: com.david.poc.springboot.crud.dao.handler
  configuration:
    map-underscore-to-camel-case: true

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/poc_microservices
    username: admin
    password: secretpassword

  flyway:
    clean-on-validation-error: true
logging:
  level:
    root: INFO
